/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface-variant": "#e2e2e2",
        "secondary-fixed-dim": "#c7c6c6",
        "on-primary-fixed-variant": "#474747",
        "primary": "#000000",
        "tertiary-fixed-dim": "#c6c6c6",
        "primary-container": "#1b1b1b",
        "on-background": "#1a1c1c",
        "inverse-on-surface": "#f1f1f1",
        "on-tertiary-fixed": "#1b1b1b",
        "on-primary-fixed": "#1b1b1b",
        "on-surface": "#1a1c1c",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "tertiary": "#000000",
        "primary-fixed-dim": "#c6c6c6",
        "on-secondary-container": "#646464",
        "on-tertiary-container": "#848484",
        "on-primary-container": "#848484",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#464747",
        "surface": "#f9f9f9",
        "tertiary-container": "#1b1b1b",
        "on-surface-variant": "#4c4546",
        "surface-tint": "#5e5e5e",
        "on-error": "#ffffff",
        "surface-dim": "#dadada",
        "primary-fixed": "#e2e2e2",
        "surface-container-high": "#e8e8e8",
        "outline-variant": "#cfc4c5",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary-fixed-variant": "#474747",
        "inverse-primary": "#c6c6c6",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "on-error-container": "#93000a",
        "surface-container": "#eeeeee",
        "inverse-surface": "#2f3131",
        "outline": "#7e7576",
        "secondary-fixed": "#e3e2e2",
        "secondary-container": "#e3e2e2",
        "secondary": "#5e5e5e",
      },
      maxWidth: {
        "container-max": "1280px"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "24px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "stack-md": "16px",
        "section-padding": "120px",
        "gutter": "32px",
        "stack-lg": "48px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "1.4", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
